CREATE TABLE public.etlcolumns (
  table_schema varchar(50),
  table_name varchar(50),
  column_name varchar(50),
  column_data_type varchar(50)
);

INSERT INTO public.etlcolumns (table_schema, table_name, column_name, column_data_type) VALUES
  ('public','battingleaders','RK','integer'),
  ('public','battingleaders','Player','varchar(50)'),
  ('public','battingleaders','Team','varchar(3)'),
  ('public','battingleaders','PlayerId','bigint'),
  ('public','battingleaders','Pos','varchar(2)'),
  ('public','battingleaders','G','integer'),
  ('public','battingleaders','AB','integer'),
  ('public','battingleaders','R','integer'),
  ('public','battingleaders','H','integer'),
  ('public','battingleaders','2B','integer'),
  ('public','battingleaders','3B','integer'),
  ('public','battingleaders','HR','integer'),
  ('public','battingleaders','RBI','integer'),
  ('public','battingleaders','BB','integer'),
  ('public','battingleaders','SO','integer'),
  ('public','battingleaders','SB','integer'),
  ('public','battingleaders','CS','integer'),
  ('public','battingleaders','AVG','real'),
  ('public','battingleaders','OBP','real'),
  ('public','battingleaders','SLG','real'),
  ('public','battingleaders','OPS','real'),
  ('public','battingleaders','IBB','integer'),
  ('public','battingleaders','HBP','integer'),
  ('public','battingleaders','SAC','integer'),
  ('public','battingleaders','SF','integer'),
  ('public','battingleaders','TB','integer'),
  ('public','battingleaders','XBH','integer'),
  ('public','battingleaders','GDP','integer'),
  ('public','battingleaders','GO','integer'),
  ('public','battingleaders','AO','integer'),
  ('public','battingleaders','GO_AO','real'),
  ('public','battingleaders','NP','integer'),
  ('public','battingleaders','PA','integer');